-- liquibase formatted sql

-- changeset ameliajochna:1691422766365-1
CREATE TABLE "users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 91) NOT NULL, "email" VARCHAR(255) NOT NULL, "hashed_password" VARCHAR(255) NOT NULL, "name" VARCHAR(255), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset ameliajochna:1691422766365-2
CREATE TABLE "tasks" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 542) NOT NULL, "owner_id" INTEGER NOT NULL, "title" VARCHAR(255), "description" VARCHAR(255), "priority" VARCHAR(6) NOT NULL, "state" VARCHAR(11), CONSTRAINT "tasks_pkey" PRIMARY KEY ("id"));

-- changeset ameliajochna:1691422766365-3
ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");

-- changeset ameliajochna:1691422766365-4
CREATE TABLE "companies" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(255) NOT NULL, "name" VARCHAR(255) NOT NULL, "hashed_password" VARCHAR(255) NOT NULL, CONSTRAINT "companies_pkey" PRIMARY KEY ("id"));

-- changeset ameliajochna:1691422766365-5
CREATE TABLE "employees" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "company_id" INTEGER NOT NULL, "user_email" VARCHAR(255) NOT NULL, CONSTRAINT "employees_pkey" PRIMARY KEY ("id"));

-- changeset ameliajochna:1691422766365-6
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
